### ISSUE TITLE
Long genres create this weird look

### ISSUE THREAD

**Issue by Xelvoren** [Vexcited/better-spotify-genres#11]
This is not ideal, buttons shifted.
![image](https://github.com/user-attachments/assets/dce86b37-8b3d-4199-b6f1-cafb2cb4c3b5)

**Comment by vexcited** [comment]
You're right, can you try again now that I removed the toggle button ? It should be less weird...

Anyway, if that's still an issue : do you have any idea on how long should I allow it to be ?

I'm asking because Spotify also doesn't limit the width, see this one for example : 
![image](https://github.com/user-attachments/assets/a1f14024-5819-4a4e-9dac-9bc7d62800a9)
and as you can see the button is also very shifted (without the plugin)

**Comment by Xelvoren** [comment]
It did not fix it sir. First image is with extension and second is without extension.

![image](https://github.com/user-attachments/assets/8afb8f7a-035a-4505-a025-c9389235adec)
![image](https://github.com/user-attachments/assets/dcda008c-15ab-4486-952f-20147757335f)

**Comment by Xelvoren** [comment]
I do not know how long you should allow it to be. All I can say is long enough that it does not shift buttons 🤷‍♀️

**Comment by vexcited** [comment]
So you want its width to depend on the title and artists widths... I'll see what I can do, not sure if it's doable with grids though

**Comment by vexcited** [comment]
I updated the plugin, it should be the same width as the title/artists containers now.

You can re-open this issue if the issue persists.

**Comment by dxcvvxd** [comment]
wish i could reopen it, it's still an issue for me
![image](https://github.com/user-attachments/assets/7657e152-f20c-4dc5-ad25-a7748a78b67f)
(the track is like 4-5 genres iirc)

also, why'd you remove the toggle button? it was pretty neat imo.

**Comment by vexcited** [comment]
> wish i could reopen it, it's still an issue for me ![image](https://private-user-images.githubusercontent.com/77129815/396817573-7657e152-f20c-4dc5-ad25-a7748a78b67f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTEwNjcsIm5iZiI6MTczNDUxMDc2NywicGF0aCI6Ii83NzEyOTgxNS8zOTY4MTc1NzMtNzY1N2UxNTItZjIwYy00ZGM1LWFkMjUtYTc3NDhhNzhiNjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA4MzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMTM0ZDZjZjFjMTgwNGQxNzVhNDc1YjQ4OGM0NjNmN2JhMzg5ODQ5N2ZjMjJiNzJkMWNlNWU1OTliNjNjNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.au2_r0_KzaWMX3AE3tvKleX2ogntTV3HhGKzsv6H88A) (the track is like 4-5 genres iirc)

This is expected, the genres' width is now fixed to the title's width or the artists' width (depending on which one is the longest)

**Comment by vexcited** [comment]
> also, why'd you remove the toggle button? it was pretty neat imo.

See https://github.com/Vexcited/better-spotify-genres/issues/8#issuecomment-2543848465

**Comment by Xelvoren** [comment]
> wish i could reopen it, it's still an issue for me ![image](https://private-user-images.githubusercontent.com/77129815/396817573-7657e152-f20c-4dc5-ad25-a7748a78b67f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NzM4ODAsIm5iZiI6MTczNDU3MzU4MCwicGF0aCI6Ii83NzEyOTgxNS8zOTY4MTc1NzMtNzY1N2UxNTItZjIwYy00ZGM1LWFkMjUtYTc3NDhhNzhiNjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDAxNTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ZTBkNmE4ZWJlNTMwZDAyMzQzMDcxN2NkMWU5YWU1NTAyMDY5MjQxZTk5N2ZhNGU3MWFjZTJhNDhiYWYxMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a5uZ0T3uNXV6815OHND0c3xyA-Yr3oYtCnfJIMToirs) (the track is like 4-5 genres iirc)
> 
> also, why'd you remove the toggle button? it was pretty neat imo.

Reopen what? You can still click on the tracks to see the full list if that's what you mean.

**Comment by dxcvvxd** [comment]
> Reopen what? You can still click on the tracks to see the full list if that's what you mean.

i was talking about reopening the issue, anyway i dont really get what you mean by "click on the tracks to see the full list"
like, click where? the genres? the track title? what would that accomplish
maybe you should put something in the readme so its easier to navigate because you fixed the width of genres (why so small though, barely one genre can fit there)

edit: found out by frantically clicking everywhere that you have to RIGHT CLICK on the genres to see the full thing
![image](https://github.com/user-attachments/assets/5938682e-a6ae-4d81-b1f8-e7096f96d3d0)
(i love how you put the tip on the genres screen which you have to access first to see it at all)

unintuitive as it gets, should at least make a button for it or something (reuse the one that you had for enabling the plugin, but make it show the genres? isnt that just better? and more intuitive?)

**Comment by vexcited** [comment]
I'm kinda lost to be honest because you both want opposite things ...

I can add a button to show all but that would result in a shift with buttons, just what I fixed in this issue.

I should try to figure out how to add settings but that's probably another issue to open I guess
