### ISSUE TITLE
[Bug] The genre list appears twice

### ISSUE THREAD

**Issue by RashiqAzhan** [Vexcited/better-spotify-genres#9]
Window is small enough to make the genre list scrolls.
![image](https://github.com/user-attachments/assets/56833870-cc4b-4b8c-8f4d-fc19ad8632e5)

The genre list appears twice for me.

Window is large enough to not make the genre list scrolls.
![image](https://github.com/user-attachments/assets/e743648d-9a5c-4c77-ad00-426b1565f86d)

Any ideas on how to fix this?

**Comment by RashiqAzhan** [comment]
It seems this is due to a conflict with this [extension](https://github.com/LucasOe/spicetify-genres). Any way to get the artist recommendation from the "What's That Genre?". That extension doesn't currently identify the genre of all songs like this one does.

**Comment by vexcited** [comment]
> That extension doesn't currently identify the genre of all songs like this one does.

Concerning `better-spotify-genres`, the genres are grabbed directly from the Spotify API without any third party API.

In the extension you linked, it seems like they have their own API (<https://github.com/LucasOe/spicetify-genres/tree/main/api> ?)

That's why some songs don't have genres, it's just the fact that Spotify still didn't put any genre on the artist you're listening to.

Concerning the issue, not sure how to resolve it if that's really a conflict with another extension.

**Comment by RashiqAzhan** [comment]
Thank you for the response. Is an artist recommendation feature based on the genre ever in the cards or out-of-scope for the project?

**Comment by vexcited** [comment]
I think it's out of scope since I can't get this data from the Spotify API.

After analyzing their code, they grab artist data and everything from their own API, see https://github.com/LucasOe/spicetify-genres/blob/e5750e06e301a8375a6515d7220a3780051b0689/src/app.tsx#L138-L149, that's why I'm unable to do it here.

**Comment by RashiqAzhan** [comment]
Understood. I'm closing this issue has it is out of scope. Appreciate the response and thank you for your project!
